-- Create constituencies table
DROP TABLE IF EXISTS datasets.constituencies;
CREATE TABLE datasets.constituencies (
    -- Unique identifier for each constituency, serves as the primary key
    constituency_id INT PRIMARY KEY,
    
    -- Name of the constituency, must not be null
    constituency_name VARCHAR(255) NOT NULL,
    
    -- ISO 3166-1 alpha-2 code
    region_code VARCHAR(2) NOT NULL
);

-- Insert constituencies data
INSERT INTO datasets.constituencies (constituency_id, constituency_name, region_code) VALUES
    (001, 'Abetifi', 'EA'),
    (002, 'Abirem', 'EA'),
    (003, 'Ablekuma Central', 'GA'),
    (004, 'Ablekuma North', 'GA'),
    (005, 'Ablekuma South', 'GA'),
    (006, 'Ablekuma West', 'GA'),
    (007, 'Abuakwa North', 'EA'),
    (008, 'Abuakwa South', 'EA'),
    (009, 'Abura-Asebu-Kwamankese', 'CN'),
    (010, 'Achiase', 'EA'),
    (011, 'Ada', 'GA'),
    (012, 'Adaklu', 'VO'),
    (013, 'Adansi-Akrofuom', 'AS'),
    (014, 'Adansi-Asokwa', 'AS'),
    (015, 'Adenta', 'GA'),
    (016, 'Afadjato South', 'VO'),
    (017, 'Afigya Kwabre North', 'AS'),
    (018, 'Afigya Kwabre South', 'AS'),
    (019, 'Afigya Sekyere East', 'AS'),
    (020, 'Afram Plains North', 'EA'),
    (021, 'Afram Plains South', 'EA'),
    (022, 'Agona East', 'CN'),
    (023, 'Agona West', 'CN'),
    (024, 'Agotime Ziope', 'VO'),
    (025, 'Ahafo Ano North', 'AS'),
    (026, 'Ahafo Ano South East', 'AS'),
    (027, 'Ahafo Ano South West', 'AS'),
    (028, 'Ahanta West', 'WE'),
    (029, 'Ajumako-Enyan-Essiam', 'CN'),
    (030, 'Akan', 'OT'),
    (031, 'Akatsi North', 'VO'),
    (032, 'Akatsi South', 'VO'),
    (033, 'Akim Oda', 'EA'),
    (034, 'Akim Swedru', 'EA'),
    (035, 'Akropong', 'EA'),
    (036, 'Akwapim South', 'EA'),
    (037, 'Akwatia', 'EA'),
    (038, 'Amasaman', 'GA'),
    (039, 'Amenfi Central', 'WE'),
    (040, 'Amenfi East', 'WE'),
    (041, 'Amenfi West', 'WE'),
    (042, 'Anlo', 'VO'),
    (043, 'Anyaa-Sowutuom', 'GA'),
    (044, 'Aowin', 'WN'),
    (045, 'Asante-Akim Central', 'AS'),
    (046, 'Asante-Akim North', 'AS'),
    (047, 'Asante-Akim South', 'AS'),
    (048, 'Asawase', 'AS'),
    (049, 'Asene/Manso/Akroso', 'EA'),
    (050, 'Ashaiman', 'GA'),
    (051, 'Asikuma-Odoben-Brakwa', 'CN'),
    (052, 'Asokwa', 'AS'),
    (053, 'Assin Central', 'CN'),
    (054, 'Assin North', 'CN'),
    (055, 'Assin South', 'CN'),
    (056, 'Asunafo North', 'AH'),
    (057, 'Asunafo South', 'AH'),
    (058, 'Asuogyaman', 'EA'),
    (059, 'Asutifi North', 'AH'),
    (060, 'Asutifi South', 'AH'),
    (061, 'Atebubu-Amantin', 'BE'),
    (062, 'Atiwa East', 'EA'),
    (063, 'Atiwa West', 'EA'),
    (064, 'Atwima-Kwanwoma', 'AS'),
    (065, 'Atwima-Mponua', 'AS'),
    (066, 'Atwima-Nwabiagya North', 'AS'),
    (067, 'Atwima-Nwabiagya South', 'AS'),
    (068, 'Awutu-Senya-East', 'CN'),
    (069, 'Awutu-Senya-West', 'CN'),
    (070, 'Ayawaso Central', 'GA'),
    (071, 'Ayawaso East', 'GA'),
    (072, 'Ayawaso North', 'GA'),
    (073, 'Ayawaso West Wugon', 'GA'),
    (074, 'Ayensuano', 'EA'),
    (075, 'Banda Ahenkro', 'BO'),
    (076, 'Bantama', 'AS'),
    (077, 'Bawku Central', 'UE'),
    (078, 'Bekwai', 'AS'),
    (079, 'Berekum East', 'BO'),
    (080, 'Berekum West', 'BO'),
    (081, 'Bia East', 'WN'),
    (082, 'Bia West', 'WN'),
    (083, 'Biakoye', 'OT'),
    (084, 'Bibiani-Anhwiaso-Bekwai', 'WN'),
    (085, 'Bimbilla', 'NO'),
    (086, 'Binduri', 'UE'),
    (087, 'Bodi', 'WN'),
    (088, 'Bole Bamboi', 'SA'),
    (089, 'Bolgatanga Central', 'UE'),
    (090, 'Bolgatanga East', 'UE'),
    (091, 'Bongo', 'UE'),
    (092, 'Bortianor-Ngleshie-Amanfro', 'GA'),
    (093, 'Bosome-Freho', 'AS'),
    (094, 'Bosomtwe', 'AS'),
    (095, 'Buem', 'OT'),
    (096, 'Builsa North', 'UE'),
    (097, 'Builsa South', 'UE'),
    (098, 'Bunkpurugu', 'NE'),
    (099, 'Cape Coast North', 'CN'),
    (100, 'Cape Coast South', 'CN'),
    (101, 'Central Tongu', 'VO'),
    (102, 'Chereponi', 'NE'),
    (103, 'Chiana-Paga', 'UE'),
    (104, 'Daboya-Mankarigu', 'SA'),
    (105, 'Dade Kotopon', 'GA'),
    (106, 'Daffiama-Bussie-Issa', 'UW'),
    (107, 'Damango', 'SA'),
    (108, 'Dome Kwabenya', 'GA'),
    (109, 'Domeabra-Obom', 'GA'),
    (110, 'Dormaa Central', 'BO'),
    (111, 'Dormaa East', 'BO'),
    (112, 'Dormaa West', 'BO'),
    (113, 'Effia', 'WE'),
    (114, 'Effiduase-Asokore', 'AS'),
    (115, 'Effutu', 'CN'),
    (116, 'Ejisu', 'AS'),
    (117, 'Ejura-Sekyedumase', 'AS'),
    (118, 'Ekumfi', 'CN'),
    (119, 'Ellembelle', 'WE'),
    (120, 'Essikado-Ketan', 'WE'),
    (121, 'Evalue-Ajomoro-Gwira', 'WE'),
    (122, 'Fanteakwa North', 'EA'),
    (123, 'Fanteakwa South', 'EA'),
    (124, 'Fomena Adansi North', 'AS'),
    (125, 'Garu', 'UE'),
    (126, 'Gomoa Central', 'CN'),
    (127, 'Gomoa East', 'CN'),
    (128, 'Gomoa West', 'CN'),
    (129, 'Gushegu', 'NO'),
    (130, 'Hemang Lower Denkyira', 'CN'),
    (131, 'Ho Central', 'VO'),
    (132, 'Ho West', 'VO'),
    (133, 'Hohoe', 'VO'),
    (134, 'Jaman North', 'BO'),
    (135, 'Jaman South', 'BO'),
    (136, 'Jirapa', 'UW'),
    (137, 'Jomoro', 'WE'),
    (138, 'Juaben', 'AS'),
    (139, 'Juaboso', 'WN'),
    (140, 'Kade', 'EA'),
    (141, 'Karaga', 'NO'),
    (142, 'Keta', 'VO'),
    (143, 'Ketu North', 'VO'),
    (144, 'Ketu South', 'VO'),
    (145, 'Kintampo North', 'BE'),
    (146, 'Kintampo South', 'BE'),
    (147, 'Komenda Edina Eguafo Abrem', 'CN'),
    (148, 'Korle Klottey', 'GA'),
    (149, 'Kpandai', 'NO'),
    (150, 'Kpando', 'VO'),
    (151, 'Kpone-Katamanso', 'GA'),
    (152, 'Krachi East', 'OT'),
    (153, 'Krachi Nchumuru', 'OT'),
    (154, 'Krachi West', 'OT'),
    (155, 'Krowor', 'GA'),
    (156, 'Kumawu', 'AS'),
    (157, 'Kumbungu', 'NO'),
    (158, 'Kwabre East', 'AS'),
    (159, 'Kwadaso', 'AS'),
    (160, 'Kwesimintsim', 'WE'),
    (161, 'Lambussie', 'UW'),
    (162, 'Lawra', 'UW'),
    (163, 'Ledzokuku', 'GA'),
    (164, 'Lower Manya Krobo', 'EA'),
    (165, 'Lower West Akim', 'EA'),
    (166, 'Madina', 'GA'),
    (167, 'Mampong', 'AS'),
    (168, 'Manhyia North', 'AS'),
    (169, 'Manhyia South', 'AS'),
    (170, 'Manso Edubia', 'AS'),
    (171, 'Manso Nkwanta', 'AS'),
    (172, 'Mfantseman', 'CN'),
    (173, 'Mion', 'NO'),
    (174, 'Mpohor', 'WE'),
    (175, 'Mpraeso', 'EA'),
    (176, 'Nabdam', 'UE'),
    (177, 'Nadowli Kaleo', 'UW'),
    (178, 'Nalerigu/Gambiga', 'NE'),
    (179, 'Nandom', 'UW'),
    (180, 'Nanton', 'NO'),
    (181, 'Navrongo Central', 'UE'),
    (182, 'New Edubease', 'AS'),
    (183, 'New Juaben North', 'EA'),
    (184, 'New Juaben South', 'EA'),
    (185, 'Nhyiaeso', 'AS'),
    (186, 'Ningo-Prampram', 'GA'),
    (187, 'Nkawkaw', 'EA'),
    (188, 'Nkoranza North', 'BE'),
    (189, 'Nkoranza South', 'BE'),
    (190, 'Nkwanta North', 'OT'),
    (191, 'Nkwanta South', 'OT'),
    (192, 'North Dayi', 'VO'),
    (193, 'North Tongu', 'VO'),
    (194, 'Nsawam Adoagyiri', 'EA'),
    (195, 'Nsuta-Kwamang-Beposo', 'AS'),
    (196, 'Obuasi East', 'AS'),
    (197, 'Obuasi West', 'AS'),
    (198, 'Odododiodio', 'GA'),
    (199, 'Odotobri', 'AS'),
    (200, 'Offinso North', 'AS'),
    (201, 'Offinso South', 'AS'),
    (202, 'Ofoase-Ayirebi', 'EA'),
    (203, 'Oforikrom', 'AS'),
    (204, 'Okaikwei Central', 'GA'),
    (205, 'Okaikwei North', 'GA'),
    (206, 'Okaikwei South', 'GA'),
    (207, 'Okere', 'EA'),
    (208, 'Old Tafo', 'AS'),
    (209, 'Prestea Huni-Valley', 'WE'),
    (210, 'Pru East', 'BE'),
    (211, 'Pru West', 'BE'),
    (212, 'Pusiga', 'UE'),
    (213, 'Saboba', 'NO'),
    (214, 'Sagnarigu', 'NO'),
    (215, 'Salaga North', 'SA'),
    (216, 'Salaga South', 'SA'),
    (217, 'Savelugu', 'NO'),
    (218, 'Sawla-Tuna-Kalba', 'SA'),
    (219, 'Sefwi Akontombra', 'WN'),
    (220, 'Sefwi Wiawso', 'WN'),
    (221, 'Sege', 'GA'),
    (222, 'Sekondi', 'WE'),
    (223, 'Sekyere Afram Plains', 'AS'),
    (224, 'Sene East', 'BE'),
    (225, 'Sene West', 'BE'),
    (226, 'Shai-Osudoku', 'GA'),
    (227, 'Shama', 'WE'),
    (228, 'Sissala East', 'UW'),
    (229, 'Sissala West', 'UW'),
    (230, 'South Dayi', 'VO'),
    (231, 'South Tongu', 'VO'),
    (232, 'Suaman', 'WN'),
    (233, 'Suame', 'AS'),
    (234, 'Subin', 'AS'),
    (235, 'Suhum', 'EA'),
    (236, 'Sunyani East', 'BO'),
    (237, 'Sunyani West', 'BO'),
    (238, 'Tain', 'BO'),
    (239, 'Takoradi', 'WE'),
    (240, 'Talensi', 'UE'),
    (241, 'Tamale Central', 'NO'),
    (242, 'Tamale North', 'NO'),
    (243, 'Tamale South', 'NO'),
    (244, 'Tano North', 'AH'),
    (245, 'Tano South', 'AH'),
    (246, 'Tarkwa Nsuaem', 'WE'),
    (247, 'Tatale-Sanguli', 'NO'),
    (248, 'Techiman North', 'BE'),
    (249, 'Techiman South', 'BE'),
    (250, 'Tema Central', 'GA'),
    (251, 'Tema East', 'GA'),
    (252, 'Tema West', 'GA'),
    (253, 'Tempane', 'UE'),
    (254, 'Tolon', 'NO'),
    (255, 'Trobu', 'GA'),
    (256, 'Twifo-Atti Morkwaa', 'CN'),
    (257, 'Upper Denkyira East', 'CN'),
    (258, 'Upper Denkyira West', 'CN'),
    (259, 'Upper Manya Krobo', 'EA'),
    (260, 'Upper West Akim', 'EA'),
    (261, 'Wa Central', 'UW'),
    (262, 'Wa East', 'UW'),
    (263, 'Wa West', 'UW'),
    (264, 'Walewale', 'NE'),
    (265, 'Wassa East', 'WE'),
    (266, 'Weija Gbawe', 'GA'),
    (267, 'Wenchi', 'BO'),
    (268, 'Wulensi', 'NO'),
    (269, 'Yagaba-Kubori', 'NE'),
    (270, 'Yapei-Kusawgu', 'SA'),
    (271, 'Yendi', 'NO'),
    (272, 'Yilo Krobo', 'EA'),
    (273, 'Yunyoo', 'NE'),
    (274, 'Zabzugu', 'NO'),
    (275, 'Zebilla', 'UE');