name: PR Checks

on:
  pull_request:
    branches:
      - dev-branch

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Run check_structure.rb
        run: ruby check_structure.rb

      - name: Verify structure
        run: |
          if [ $? -eq 0 ]; then
            echo "Structure verification successful."
            exit 0
          else
            echo "Structure verification failed. Please fix the issues."
            exit 1
          fi
